# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python27:
      python.version: '2.7'



steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- script: python "mul.py"
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('This is Section 1 Azure Demonstration')
      print('KL-CSE')